Pagliuca#6408
undefined-academy/semana-2 pull request #103
Opened 2023-03-17 05:43 UTC by Breakingsoft

Semana 2

2023-03-17 15:59 UTC, Alexis033 requested changes
Hola, en general lo veo bien, hay algunas cositas que podrían revisarse, y quedo atento cuando subas el formulario para darle el approve.

Y si puedes echarle un ojito al mío te lo agradezco: [PR](https://github.com/undefined-academy/semana-2/pull/8)

2023-03-17 15:59 UTC, Alexis033 commented on student-cvs/pagliuca-6408/index.html
> +        <h2>🐧 Bye say TUX</h2>
Este h2 no debería ser un titulo, es más como un <p> o un <span> si quieres resaltarlo puedes ponerle un <strong> o un <em>

2023-03-17 15:59 UTC, Alexis033 commented on student-cvs/pagliuca-6408/index.html
> +      <br>
estos <br> saltos de línea puedes ahorrártelos y ponerlos con el css dándoles margin o padding a los elementos.

2023-03-17 19:09 UTC, lucianogarriga requested changes
Adhiero a los comentarios realizados por Alexis. Habría que revisar la jerarquía de unos títulos (h2 y h3), y unos saltos de línea y estilos que podrían darse desde el CSS para evitar el agregado de etiquetas HTML a los fines de un código más limpio. 
Lo demás lo veo muy bien realizado, una vez que corrijas esas cosas me avisas así te apruebo tu PR Alexander!

2023-03-17 19:09 UTC, lucianogarriga commented on student-cvs/pagliuca-6408/index.html
> +      <h4><strong><em>Visita mi <a href="https://github.com/Alexander-Solis-Brenes">github</a></em></strong></h4>
Tanto los saltos de linea, como los estilos (strong, em) seria recomendable que los realices mediante un archivo CSS, mediante el uso de clases.

2023-03-18 05:10 UTC, Breakingsoft commented on student-cvs/pagliuca-6408/index.html
> +            <h3>Soy desarrollador front-end junior y actualmente soy estudiante de Innovacción Virtual (Microsoft X Launch LATAM) , ONE (Oracle Next Academy, ALURA LATAM)
Listo estimado Alexis, ya lo cambie

2023-03-18 05:10 UTC, Breakingsoft commented on student-cvs/pagliuca-6408/index.html
> +        <h2>🐧 Datos Linux 🐧</h2>
Este también

2023-03-18 05:10 UTC, Breakingsoft commented on student-cvs/pagliuca-6408/index.html
> +        <h2>🐧 Bye say TUX</h2>
Toda la razón, listo

2023-03-18 05:10 UTC, Breakingsoft commented on student-cvs/pagliuca-6408/index.html
> +      <br>
Listo, encerré en div's

2023-03-18 05:11 UTC, Breakingsoft commented
> Hola, en general lo veo bien, hay algunas cositas que podrían revisarse, y quedo atento cuando subas el formulario para darle el approve.
> 
> Y si puedes echarle un ojito al mío te lo agradezco: [PR](https://github.com/undefined-academy/semana-2/pull/8)

Gracias por tus observaciones, son de mucha ayuda, y claro, ya me doy la vuelta por el tuyo, gracias de verdad!

2023-03-18 05:13 UTC, Breakingsoft commented on student-cvs/pagliuca-6408/index.html
> +      <h4><strong><em>Visita mi <a href="https://github.com/Alexander-Solis-Brenes">github</a></em></strong></h4>
Perfecto Luciano, ya me pongo en eso, muy agradecido con tus recomendaciones.

2023-03-18 16:43 UTC, Alexis033 approved these changes

2023-03-18 16:43 UTC, Alexis033 commented on student-cvs/pagliuca-6408/css/style.css
> +  nav li a:hover {
Hola, me gusta el formulario, pero quizás podrías hacer más sutil el hover que vuelva todo negro es muy brusco con la paleta de coleres que estás trabajando.

2023-03-18 16:43 UTC, Alexis033 commented on student-cvs/pagliuca-6408/css/style.css
> +    color: #ffffff;
Ten cuidado con el contraste entre este color de letra y el de tu fondo, lo noto un poco bajo, lo cual dificulta leerlo.

2023-03-27 21:09 UTC, Breakingsoft commented on student-cvs/pagliuca-6408/css/style.css
> +    color: #ffffff;
Hola @Alexis033, ya aplique tus recomendaciones, en código paso con la nota mínima, pero en diseño creo que repruebo XD, gracias por tu apoyo.

2023-03-27 21:28 UTC, Alexis033 commented on student-cvs/pagliuca-6408/css/style.css
> +    color: #ffffff;
jejeje yo creo que a casi todos los que no hemos visto diseño nos cuesta, pero es cosa de ir viendo muchas paginas y practicando para cogerle el truco.

2023-03-31 06:39 UTC, Breakingsoft commented on student-cvs/pagliuca-6408/index.html
> +      <h4><strong><em>Visita mi <a href="https://github.com/Alexander-Solis-Brenes">github</a></em></strong></h4>
Hola, ya aplique los cambios, saludos!

2023-04-04 02:03 UTC, jaiver-1 approved these changes
Como sugerencia dejar en la descripción del pull lo que se realizo en la actividad las actividaes que estas realizando

2023-04-04 14:20 UTC, lucianogarriga commented on student-cvs/pagliuca-6408/index.html
> +      <h4><strong><em>Visita mi <a href="https://github.com/Alexander-Solis-Brenes">github</a></em></strong></h4>
Perfecto ahora lo reviso, disculpa mi demora!

2023-04-04 14:46 UTC, lucianogarriga approved these changes
Luego de las recomendaciones realizadas, considero que el PR se encuentra apto para ser aprobado! Felicidades!

2023-04-27 13:12 UTC, dfm555 requested changes

2023-05-03 03:42 UTC, Breakingsoft commented on .vscode/settings.json
Listo, muchas gracias por tu observación 👍

2023-05-03 03:43 UTC, Breakingsoft commented on README.md
Elimine lo que estaba de más, muchas gracias 👌

2023-05-03 13:10 UTC, dfm555 requested changes

2023-05-03 13:10 UTC, dfm555 commented on .gitignore
Revisa que este archivo debe ser igual al del repo original

Tenés conflictos

2023-05-04 02:56 UTC, Breakingsoft commented on .gitignore
Listo con el gitignore, disculpa los inconvenientes, igual tengo un problema con el  README.md, pero lo he revisado varias veces, y lo tengo idéntico, no entiendo cual es el error 😢😢😢

2023-05-04 03:06 UTC, dfm555 commented on .gitignore
Agrégame a tu repositorio  como colaborar te ayudo.

2023-05-04 03:18 UTC, dfm555 approved these changes
Listo, resueltos los conflictos.

2023-05-04 03:18 UTC, merged