ajustes HTML a HTML semantico
undefined-academy/semana-2 pull request #106
Opened 2023-03-17 15:28 UTC by andreslipe94

2023-03-17 19:39 UTC, lucianogarriga requested changes
En términos generales se ve bien tu trabajo, con código prolijo y estructurado. Un detalle a tener en cuenta, es que has realizado tu pull request sin ningún comentario ni archivo .md (lo cuál fue uno de los primeros requisitos exigidos en el bootcamp). Una vez realizado eso avísame para aprobar tu PR!

2023-03-17 19:39 UTC, lucianogarriga commented on student-cvs/andreslipe94-3516/index.html
> +        <section id="text">
La sección de contacto se recomendaría colocar más al final de la página

2023-03-17 20:46 UTC, andreslipe94 commented
Ajustes de HTML Semantico

2023-03-18 18:07 UTC, andreslipe94 commented
se añade al HTML organizado el formulario de contacto básico

2023-03-19 12:57 UTC, VALNTNO approved these changes
buen trabajo

2023-07-04 02:49 UTC, closed without merging