aplicando html semantico a perfil de github
undefined-academy/semana-2 pull request #109
Opened 2023-03-17 18:40 UTC by raf81t

Se aplica html semantico a perfil de GitHub.

2023-04-03 16:13 UTC, ga-b0 requested changes

2023-04-03 16:13 UTC, ga-b0 commented on student-cvs/raf81t-7892/index.html
> +    <article class="article">
Creo que aquí sería mejor utilizar la etiqueta `<main>` en lugar de un `<article>` para que se diferencia mejor el contenido principal que en tu caso sería el CV, y separarlo de los comandos, aunque creo que para esta práctica no será necesario colocarlos pues ya estamos trabajando de lleno en nuestra hoja de vida

2023-04-03 16:13 UTC, ga-b0 commented on student-cvs/raf81t-7892/form.html
> +            <button>Enviar</button>
El button como tal no enviará el formulario, para ello debes definirlo como tipo "submit", y puedes intentar realizar el ejercicio que dejó de último Guillermo, el de prevenir el comportamiento por defecto del formulario, que es enviarlo, pero para ello debes agregar código JavaScript

2023-04-03 19:23 UTC, raf81t commented on student-cvs/raf81t-7892/index.html
> +    <article class="article">
Buenas tardes! ya he realizado los cambios que me has indicado. Gracias por hacer la revisión.

2023-04-03 19:26 UTC, raf81t commented on student-cvs/raf81t-7892/form.html
> +            <button>Enviar</button>
Hola! he revisado y cambiado la función en el botón y colocado JS para prevenir el comportamiento del form.
Gracias por revisar el pull requests.

2023-04-04 14:26 UTC, ga-b0 approved these changes

2023-07-02 02:53 UTC, closed without merging