semana 2-clase 1-html semantico
undefined-academy/semana-2 pull request #128
Opened 2023-03-18 22:48 UTC by giovanyosorio

Semana 2

Clase html semantico

2023-03-19 01:51 UTC, giovanyosorio commented
Se creo una seccion de contacto usando formularios aplicando css

2023-03-19 16:11 UTC, Alexis033 requested changes
Hola, te hice algunos comentarios, espero que te sirvan.

2023-03-19 16:11 UTC, Alexis033 commented on student-cvs/giot99-7609/styles.css
> +    background: papayawhip;
Hola, no sé si es intencional, pero si no, podrías revisar para que el fondo del <select> no sea igual que el de la página, pasa desapercibido de esa forma.  También puedes considerar cambiarle el estilo a las etiquetas < a > para que se vean más a juego con tu página y no con su diseño por defecto.

2023-03-19 16:11 UTC, Alexis033 commented on student-cvs/giot99-7609/index.html
> +        <p>skills</p>
Este < p > más que un párrafo debería ser algún subtitulo un h2 o h3, mira que la función semántica que cumple es englobar la lista de más abajo.

2023-03-19 16:11 UTC, Alexis033 commented on student-cvs/giot99-7609/index.html
> +        <h3>
Aquí, este h3  sería más bien un párrafo ya que brinda información sobre ti que es lo que dice el titulo de arriba.

2023-03-20 14:32 UTC, giovanyosorio commented on student-cvs/giot99-7609/styles.css
> +    background: papayawhip;
Hola , espero que es muy bien.
Deje por defecto el color negro, para el tema de los colores, no soy muy bueno en diseño por ahora jejeej, estare mejorando mi css con el transcurso del bootcamp

2023-03-20 14:33 UTC, giovanyosorio commented on student-cvs/giot99-7609/index.html
> +        <h3>
Mismo caso, semanticamente deberia sera un P

2023-03-20 14:33 UTC, giovanyosorio commented
Cambios realizados
Con respecto al css tengo que estudiar un poco mas sobre el diseño

2023-03-20 15:03 UTC, Alexis033 commented on student-cvs/giot99-7609/index.html
> +        <p>skills</p>
Perdón debí ser más específico, me refería al < p > de skills que parece más un subtitulo.

2023-03-20 15:03 UTC, Alexis033 commented on student-cvs/giot99-7609/index.html
> +        <h3>
y aquí lo mismo, me refería a que "más sobre mi" era un titulo (h2 o h3) y lo que dice que estás estudiando debía ser un párrafo. Lamento la confusión.

2023-03-20 18:15 UTC, giovanyosorio commented on student-cvs/giot99-7609/index.html
> +        <h3>
"mas sobre mi " queda como un h2 y lo demas como parrafo

2023-03-20 18:20 UTC, Alexis033 approved these changes

2023-03-21 02:50 UTC, nanpipe approved these changes
Muy bien, todo segun lo solicitado. Me hubiera gustado ver un poco más de información en el CV, sobretodo para entender nivel de experticie en las tecnologias.

2023-03-21 13:30 UTC, merged