Ejercio S2 C3 HTML Semático
undefined-academy/semana-2 pull request #131
Opened 2023-03-19 09:22 UTC by marcospenalosa

Agregado HTML **semántico** a *index.html*

2023-03-20 20:50 UTC, dlozanoc82 commented on student-cvs/murquis-5340/contact.html
> +                        <label>He<input type="radio" id="pronoun" name="pronoun" value="he"></label>
El valor del atributo ```id = "pronoun"``` debe ser único dentro del documento HTML. Este valor se usa para apuntar a una declaración de estilo específica en una hoja de estilo. También lo utiliza JavaScript para acceder y manipular el elemento con la identificación específica.

2023-03-20 20:53 UTC, dlozanoc82 requested changes
Realizar el cambio comentado en el archivo contact.html

2023-03-20 21:39 UTC, dlozanoc82 approved these changes
Bueno trabajo 👏

2023-03-22 08:12 UTC, NoaSalgado approved these changes
Buen trabajo!! 💪 Sólo debes hacer una pequeña modificación en el formulario

Un saludo!

2023-03-22 08:12 UTC, NoaSalgado commented on student-cvs/murquis-5340/contact.html
> +                        <label>She<input type="radio" id="she" name="pronoun" value="she"></label>
Los `<input type="radio">` deben tener el mismo valor para el atributo `name` para que el usuario sólo pueda marcar una de las opciones. 
Tal como lo tienes es posible seleccionar más de una opción. Cuando este sea el comportamiento deseado, el `type` a utilizar sería `checkbox`

2023-03-22 18:22 UTC, merged