HTML Semántico
undefined-academy/semana-2 pull request #150
Opened 2023-03-20 03:06 UTC by fedegomezc

Realice fork del repositorio semana 2
Clone el repositorio a mi repo local
Cree una carpeta con mi nombre de usuario en discord dentro de /students-ccs
Agregue los archivos html y css de la semana 1 y cambié a etiquetas semánticas
Subi los cambios al repositorio remoto (forked) y desde el mismo hice el PR

2023-03-20 04:47 UTC, Cristhian-Medina requested changes

2023-03-20 04:47 UTC, Cristhian-Medina commented on student-cvs/Fede.GC-5692/index.html
> +    <div class="tracking-in-expand">
Hola Federico,
Te recomiendo que elimines esta etiqueta “div” y dejes solo la etiqueta “header”, me parece que le daría más sentido.

2023-03-20 04:47 UTC, Cristhian-Medina commented on student-cvs/Fede.GC-5692/index.html
> +    <section>
Te recomiendo que cambies la etiqueta "section" por la etiqueta "main" ó en vez de cambiarla podrías encerrarla si tienes pensado agregar más secciones al documento.

2023-03-20 21:32 UTC, fedegomezc commented on student-cvs/Fede.GC-5692/index.html
> +    <section>
Perfecto. Por el momento voy a cambiar a la etiqueta main y luego si agrego más de una sección utilizaré la etiquetas 'section'

2023-04-16 22:47 UTC, INGCapaDev approved these changes
Buen trabajo, implementaste los cambios que se te sugirieron lastima no siguio con la revision el otro compañero.

2023-04-19 01:45 UTC, Cristhian-Medina approved these changes

2023-04-19 02:53 UTC, merged