Second Week, Pull Request
undefined-academy/semana-2 pull request #158
Opened 2023-03-20 16:43 UTC by Wannmi

# Semana 2  

## Semántica y Formularios 👨‍💻

### En este Pull Request contendrá dos grandes actualizaciones.

1. Primer modificación 📰
Aplicamos **HTML Semántico** al proyecto desarrollado en la semana 1, esto le agrega mas **valor** al contenido ya que el sitio web será mas _accesible_ y _significativo_ para los motores de búsqueda. 

2.  Segunda modificación 🗃
Al proyecto le agregamos un **formulario**, ya que es un método para que el _usuario_ envié _información_ al servidor.

2023-03-23 17:58 UTC, JoseCamilo84 requested changes

2023-03-23 17:58 UTC, JoseCamilo84 commented on student-cvs/DameAsado-6873/index.html
> +<!DOCTYPE html>
Hola, buen trabajo, aunque no veo el formulario

2023-03-23 18:06 UTC, Wannmi commented on student-cvs/DameAsado-6873/index.html
> +<!DOCTYPE html>
Hola, no, todavia no hice el commit del formulario, en este momento esta en desarrollo.

2023-03-23 20:56 UTC, JoseCamilo84 commented on student-cvs/DameAsado-6873/index.html
> +<!DOCTYPE html>
ah ok listo, si puedes también revisa el mío ya que sólo tengo un review

2023-04-09 03:57 UTC, JoseCamilo84 approved these changes

2023-05-08 22:12 UTC, JoeOsG approved these changes
### Bien

2023-06-08 02:44 UTC, closed without merging