Semana 2 -Html semantico
undefined-academy/semana-2 pull request #175
Opened 2023-03-21 10:59 UTC by gabobregon89

Actualice un poco mi index.html aplicando html semántico.

2023-03-23 17:47 UTC, JoseCamilo84 requested changes

2023-03-23 17:47 UTC, JoseCamilo84 commented on student-cvs/GabrielObregon-7536/index.html
> +            <header><img src="header.jpg" alt=""></header>
Hola deberías de colocarle alguna descripción a la propiedad "alt" por la accesibilidad

2023-03-23 17:47 UTC, JoseCamilo84 commented on student-cvs/GabrielObregon-7536/index.html
> +            <div>
también podrías usar clases para un mejor css

2023-03-26 19:10 UTC, gabobregon89 commented on student-cvs/GabrielObregon-7536/index.html
> +            <header><img src="header.jpg" alt=""></header>
Gracias por las correcciones, ahi ya agregue eso que faltaba y modifique la info del archivo con los datos de mi CV.

2023-04-05 21:50 UTC, manuelmannuel approved these changes
Buen trabajo, sigamos mejorando.

2023-04-09 03:54 UTC, JoseCamilo84 approved these changes

2023-04-10 09:14 UTC, merged