semana-2
undefined-academy/semana-2 pull request #195
Opened 2023-03-23 16:48 UTC by dhdarken

> **Ejercicio de calentamiento - Ejercicio 01**:

En el ejercicio de calentamiento definimos el valor de Hugo (let hugo = 15) y solo se imprime en pantalla lo que poseen cada uno si el valor total entre los 3 es 85
En el ejercicio 01 hay que demostrar que typeof obj === "object" para ello cree una function que queda definida asi **_function idObjeto(obj) { return typeof obj === "object" && obj !== null;_ }**

Le agrego la condicionante de **_&& obj !== null_**; para que la funcion retorne si obj es un objeto (true) o no (false)
Mando a imprimir en pantalla **console.log(idObjeto(obj)** para que muestre el resultado.

> Ejercicio de calentamiento - Ejercicio 02:

En el ejercicio de calentamiento simplemente define un objeto human que tiene caracteristicas de mi persona (nombre, edad, estatura, sexo etc..) mi objeto quedo de esta manera:
const human = { name: "julian", edad: 28, sexo: "Masculino", estatura: 1.70, }

> En el ejercicio 02  **typeof arr === "object"** no funcionaba debido a que solo funciona para los objetos, por esto cuando definia una function de esta manera **_function idArray(arr){typeof arr === "object && arr !== null_** siempre retornaba false o la consola daba error cuando mandaba a imprimir el resultado de la funcion en pantalla.

Por ello me di la tarea de buscar en google un poco sobre los arrays y encontre que para demostrar si un array es true o false habia que mandar a llamar a **Array.isArray()**
Sustituimos **Array.isArray()** por typeof y mande a llamar a mi funcion en pantalla.

> Ejercicio de calentamiento - Ejercicio 03:

1. Verifique el Outline de mi HTML haciendo un Copy & Paste en [https://validator.w3.org/nu/#textarea](https://github.com/undefined-academy/semana-2/blob/main/url)

2. Realice las correcciones que me indico y valide que todo tuviera sentido semantico

3. Agregue las etiquetas semanticas vistas en clase en los apartados de mi hoja de vida (index.html) tal como header, article, section y footer

4. Hice fork del repositorio de semana-2 de Undefined Academy

5. Clone el fork en mi carpeta local y añadi mi index.html en repositorio local

6. Realice mi Pull Request.

> Ejercicio 04:

1. Cree un formulario con la estructura vista en clase.

2. en otro documento HTML y cree un nuevo css para darle estilo a el form lo hice con la etiqueta footer por que pienso que este form encajaría  en mi hoja de vida vista en la semana 1 en la parte de abajo.

3. Encontre en Google una function que me deshabilita el boton por default,esta se llama preventdefault. debemos llamar el form por medio de el id con **_DOM_** con: 

    **_const form = document.getElementById("form");
    form.addEventListener("submit", function(event) {
    event.preventDefault();
    form.method="post";
    form.submit(); _**
});
4. le di todos los estilos aplique flexbox para darle estilo y centrar todo lo que queria que se viera mas ameno para todos.

2023-03-28 19:46 UTC, lllariogonzalez approved these changes

2023-03-28 22:59 UTC, diirf requested changes
Hola! Muy buena tu página. Te he dejado solo unos pequeños cambios.

2023-03-28 22:59 UTC, diirf commented on student-cvs/dhdarken-5806/form.html
> +              <input type="radio" id="age_1_to_20" /><label
Falta validar el radio button

2023-03-28 22:59 UTC, diirf commented on student-cvs/dhdarken-5806/index.html
> +    />
Deberías añadir un link que te lleve al formulario para no tener que buscar el archivo

2023-04-12 16:21 UTC, dhdarken commented on student-cvs/dhdarken-5806/form.html
> +              <input type="radio" id="age_1_to_20" /><label
hola, buen dia . me podrias explicar un poco esto de validar? la verdad soy nuevo y apenas voy aprendiendo muchas gracias.

2023-04-12 16:22 UTC, dhdarken commented on student-cvs/dhdarken-5806/index.html
> +    />
ya lo hice espero solucionar lo de el input radio para subir todo.

2023-04-14 20:18 UTC, diirf commented on student-cvs/dhdarken-5806/form.html
> +              <input type="radio" id="age_1_to_20" /><label
Te quedaría algo así `<input name=radio type="radio" id="age_1_to_20" required/>`, hazlo por cada input. El required hará la validación pero necesitas darle un mismo "name" a cada uno para que entienda que son del mismo grupo.

2023-04-14 20:29 UTC, dhdarken commented on student-cvs/dhdarken-5806/form.html
> +              <input type="radio" id="age_1_to_20" /><label
oh lo hice pero con name="edad" . ya hice push de los cambios . muchas gracias

2023-04-14 22:38 UTC, diirf approved these changes

2023-04-27 13:06 UTC, merged