w2 class 3: semantic HTML
undefined-academy/semana-2 pull request #2
Opened 2023-03-14 05:50 UTC by beresdev

- En esta clase aprendí a usar la herramienta del [validador](https://validator.w3.org/nu/)
- Los errores corregidos fueron referentes a:
> Agregar atributo _alt_ a todas las imágenes
> Quitar etiqueta de cierre de algunas etiquetas `<img>`, ya que es una etiqueta de self-closing

2023-03-15 01:44 UTC, DevOld112 approved these changes
Codigo entendible, limpio y ordenado :)

2023-03-28 22:00 UTC, diirf requested changes
Hola, me ha gustado mucho tu página! Te dejé solo una recomendación. Veo que tienes un solo commit, recuerda hacer el segundo agregando el formulario.

2023-03-28 22:00 UTC, diirf commented on student-cvs/beresdev-4037/index.html
> +<!DOCTYPE html>
Te recomiendo centrar un poco más la página

2023-03-28 22:00 UTC, diirf commented on student-cvs/beresdev-4037/index.html
> +        </section>
Falta el formulario

2023-04-02 20:03 UTC, merged