semantic HTML added
undefined-academy/semana-2 pull request #200
Opened 2023-03-23 20:45 UTC by cristinacdm

I ran both HTML on the **validator.w3.org** website and applied the changes I deemed necesaries and corrected some errors.

>I divided mi CV in two for styling purposes, so the index.html page can be considered a front page.

2023-03-25 19:55 UTC, Danlarte commented
Excelente trabajo.

2023-04-04 23:25 UTC, manuelmannuel approved these changes
Excelente trabajo, muy creativo, solo unas observaciones, no siempre es necesario crear archivo css por archivo html se estan repitiendo propiedades que se pueden reutilizar como el caso de los botones y walpaper, otra recomendacion es no cargar imagenes en git lo ideal seria que las imagenes utilizadas fueran enlaces.

2023-04-05 17:03 UTC, Danlarte commented
> Excelente trabajo, muy creativo, solo unas observaciones, no siempre es necesario crear archivo css por archivo html se estan repitiendo propiedades que se pueden reutilizar como el caso de los botones y walpaper, otra recomendacion es no cargar imagenes en git lo ideal seria que las imagenes utilizadas fueran enlaces.

Hola Manuel, muchas gracias por tus comentarios. Tendré en cuenta todo lo que me señalaste para implementar en los proximos PR , muchas gracias una vez más, saludos.

2023-04-05 21:45 UTC, cristinacdm commented
@manuelmannuel gracias por el comentario, el problema con la imagen del wallpaper es que es una modificación mía hecha en photoshop, y las paginas de estilos intentaré ponerlo todo en la misma, pero al haber tantos elementos me parecía más claro hacerlo así al principio.

2023-04-06 14:53 UTC, MauBedoya requested changes
Quedaron muy buenos los estilos me parece, y eso que lo vi sin descargar las imágenes 😅.
Creo que habría que darle una mirada a los `article` y `main` de tus páginas y con eso estaría, ahh y como estas utilizando varias páginas y estilos, sería bueno que para el siguiente PR utilices un servicio como [GitHub Pages](https://pages.github.com/) para facilitar la revision de tu código y ver los estilos junto a las imágenes 👀

2023-04-06 14:53 UTC, MauBedoya commented on student-cvs/Lian-0550/index.html
> +    <main class="content">
me parece que este **main** podría reemplazarse por un **div**, esto porque se está usando para englobar todo el contenido cuando el objetivo es que englobe solo tu contenido principal y relacionado, tomando en cuenta eso, la parte de "contact" y el nav quedarían fuera del contenido principal.
pienso que tu contenido principal es lo que englobaste con el **article** que contiene tu descripción, que parece ser lo "principal" de la página.

2023-04-06 14:53 UTC, MauBedoya commented on student-cvs/Lian-0550/main.css
> +  overflow-x: hidden;
en esta parte no estoy seguro de si es por una diferencia de dispositivos, pero en mi caso no se da un scroll horizontal, se da uno vertical, que queda un poco raro al tratarse de contenido que parece que querías que quede centrado verdad? 👀, creo que esto se "soluciona" quitando el padding que pusiste en el `.content` del media query de 800px o si no directamente cambiando a overflow-y: hidden

2023-04-06 14:53 UTC, MauBedoya commented on student-cvs/Lian-0550/index.html
> +            <article>
de este **article** te comentaba, al ser un article se da a entender que el contenido no está relacionado al contexto de tu página principal y queda como si fuera un artículo externo.

2023-04-06 14:53 UTC, MauBedoya commented on student-cvs/Lian-0550/aboutme.html
> +        <article>
aquí la misma idea sobre el **main** y el **article** que te comente en el index.html

2023-04-06 16:51 UTC, Danlarte commented
> Quedaron muy buenos los estilos me parece, y eso que lo vi sin descargar las imágenes 😅. Creo que habría que darle una mirada a los `article` y `main` de tus páginas y con eso estaría, ahh y como estas utilizando varias páginas y estilos, sería bueno que para el siguiente PR utilices un servicio como [GitHub Pages](https://pages.github.com/) para facilitar la revision de tu código y ver los estilos junto a las imágenes 👀

Hola Mau, muchas gracias por tus comentarios, tendré en cuenta todo lo que me estas señalando para poder realizar los ajustes en los próximos PR. Voy a tomar tus consejos de [GitHub Pages] , no estoy muy familiarizado con esta plataforma, si bien la conozco hace bastante se muy poco sobre ella y lo que vos me señalaste me sirve para aprender, asi que mil gracias por tus revisiones. Saludos Mau y gracias una vez más.

2023-04-07 14:37 UTC, cristinacdm commented
> Quedaron muy buenos los estilos me parece, y eso que lo vi sin descargar las imágenes 😅. Creo que habría que darle una mirada a los `article` y `main` de tus páginas y con eso estaría, ahh y como estas utilizando varias páginas y estilos, sería bueno que para el siguiente PR utilices un servicio como [GitHub Pages](https://pages.github.com/) para facilitar la revision de tu código y ver los estilos junto a las imágenes 👀

Gracias por el comentario Mau, he estado mirando lo del Github pages y si no me equivoco sería crear un nuevo commit acabado en github.io con los html los estilos y las imágenes y github cargaría la pagina, no?

2023-04-07 14:44 UTC, cristinacdm commented on student-cvs/Lian-0550/main.css
> +  overflow-x: hidden;
> en esta parte no estoy seguro de si es por una diferencia de dispositivos, pero en mi caso no se da un scroll horizontal, se da uno vertical, que queda un poco raro al tratarse de contenido que parece que querías que quede centrado verdad? 👀, creo que esto se "soluciona" quitando el padding que pusiste en el `.content` del media query de 800px o si no directamente cambiando a overflow-y: hidden

La idea del padding es que en una pantalla de pc no quede pegado a los bordes, y que en ningún caso se genere un scroll lateral, en un principio menos de 800px debería de saltar el media para pantallas móvil y ahí sí que se muestra un scroll vertical y la imagen pasaría a posicionarse encima del texto. Yo lo ejecuto en edge y no me da ningún problema.

2023-04-07 14:48 UTC, cristinacdm commented on student-cvs/Lian-0550/main.css
> +  overflow-x: hidden;
La idea es que no se genere nunca un scroll lateral, en pantalla inferior a 800px debería saltar al media de movil y ahí si que se generaría un scroll vertical ya que la imagen pasaría a colocarse encima del texto. Yo lo visualizo en edge y no me da ningún problema.

2023-04-07 19:21 UTC, MauBedoya commented
@cristinacdm
Puedes hacer la prueba siguiendo estos pasos:
1. Crea un Nuevo repositorio **publico** que tenga como nombre: `cristinacdm.github.io`.
2. Clona ese nuevo repositorio en tu equipo (de la misma manera que clonaste los repos de semana 1 y semana 2) y copias los archivos necesarios para tu CV dentro de esa carpeta. Debería quedarte algo así:
> Por si las dudas te recomendaría que cambies los enlaces de tus html a relativos, por ejemplo, de `/main.css` a solo `main.css`.
```
cristinacdm.github.io/
    index.html
    main.css
    aboutme.html
    aboutme.css
    contact.html
    contact.css
    images/
```
3. Ahora subes esos archivos al repo de GitHub, como ya sabes, con el git add, commit y push de toda la vida.
4. En el repositorio de GitHub vas a la pestaña de **settings** y buscas **pages** en el menu de la izquierda.
5. Una vez en **pages** deberías ver lo de la siguiente imagen, tu **source** debe estar en `deploy from a branch` y tu **branch** en `master` o `main` (si no creaste un repo desde cero antes quizá es `master` por defecto).
![image](https://user-images.githubusercontent.com/111880575/230663007-ea6a4c20-3aaa-4b96-aee9-33c503928e1d.png)
6. Ahora solo le das a `save`, esperas unos 5-10min y si todo salió bien te aparecerá el mensaje de `Your site is live at ....` como en la imagen.

Creo que con eso debería estar, pero si salta algún error mandas un mensaje 👀

2023-04-07 19:28 UTC, MauBedoya commented on student-cvs/Lian-0550/main.css
> +  overflow-x: hidden;
ahh cierto, el padding es necesario en ciertos anchos cercanos a 800px, no vi bien eso, y lo del scroll vertical en desktop supongo que es por el alto de la pantalla en la que revise 😅

2023-04-11 16:44 UTC, cristinacdm commented on student-cvs/Lian-0550/aboutme.html
> +        <article>
Gracias por las correcciones, he modificado los 3 html, creo que ahora está más claro el contenido ^^

2023-04-11 17:13 UTC, cristinacdm commented
Muchas gracias @MauBedoya por la explicación tan detallada de cómo funcionan las pages de git 😍 . Acabo de subirla, así que supongo que en un rato estará disponible.

2023-04-11 17:33 UTC, MauBedoya commented
> Muchas gracias @MauBedoya por la explicación tan detallada de cómo funcionan las pages de git 😍 . Acabo de subirla, así que supongo que en un rato estará disponible.

Sii la acabo de ver, te quedo muy buena la página con las imágenes y estilos 👌👌.
Solo un detalle, usaste dos carpetas que contienen tus archivos, por eso el link en el que se puede ver tu página es:
`https://cristinacdm.github.io/Page-github/CV-semana-2/index.html`
Mientras que si sacas los archivos de esas carpetas y haces commit tu link sera este:
`https://cristinacdm.github.io`
Esto quizá ya lo sabes pero te lo comento por si acaso, a mí me paso eso una de las primeras veces y no sabía por qué no funcionaba con el link corto 😅

2023-04-11 17:37 UTC, cristinacdm commented
Ahhh vale, me estaba volviendo un poco loca buscando porqué no funcionaba XD. Entonces simplemente dejo los archivos en el home sin ponerlos en carpetas?

2023-04-11 17:37 UTC, MauBedoya approved these changes

2023-04-11 17:41 UTC, MauBedoya commented
> 

jajaja justamente te paso eso entonces.
Si si, puedes sacar los archivos de las carpetas y github tendría que reconocer automáticamente tu archivo html sin tener que entrar a ninguna carpeta, luego igual, esperas unos minutos y ya debería quedar

2023-05-24 02:26 UTC, closed without merging