Semana 2 - Html semántico
undefined-academy/semana-2 pull request #21
Opened 2023-03-14 21:41 UTC by MariaSolArroyo

#  🤓 Semana 2
## HTML SEMÁNTICO

- Me sirvió mucho para este **ejercicio** volver a repasar lo que mis compañeros me ayudaron la primera vez con **GIT** así como el uso del **VALIDATOR** para verificar que mi código estuviera en buen camino.
-  Cambié mi hoja de vida por etiquetas para lograr un **HTML SEMÁNTICO.**

2023-03-19 11:08 UTC, NoaSalgado commented on student-cvs/MariaSolArroyo-9830/html/contacto.html
> +    <link rel="stylesheet" href="/css/style.css">
Debes modificar la ruta de la hoja de estilos a `href="../css/style.css"`. Como el archivo html no se encuentra en el directorio raíz, debes indicarle que primero debe  "salir" del directorio en el que se encuentra para poder acceder al directorio que contiene la hoja de estilos

2023-03-19 11:10 UTC, NoaSalgado commented on student-cvs/MariaSolArroyo-9830/html/contacto.html
> +                <label for="description">Consultas Generales</label>
Creo que aquí emmet te ha jugado una mala pasada y en vez de obtener `<div class="form-group>"` se ha creado el elemento `<div-form-group>`. A nivel de estilos no influye ya que aplica el margen inferior del elemento anterior

2023-03-19 11:16 UTC, NoaSalgado requested changes
Hola!!!

Has hecho un buen trabajo aplicando HTML semántico, y el formulario que has incluido es super completo, enhorabuena!! 💪

Tan sólo te faltaría incluir el script para prevenir el comportamiento por defecto al enviar el formulario. Cuando lo tengas avísame para aprobar la pull request 😃. Te dejo este [enlace](https://keepcoding.io/blog/evento-submit-en-javascript/) por si te sirve de ayuda

Saludos!!

2023-03-20 01:22 UTC, MariaSolArroyo commented on student-cvs/MariaSolArroyo-9830/html/contacto.html
> +    <link rel="stylesheet" href="/css/style.css">
muchas gracias por comentarmelo ya he corregido esto y tambien lo del div, aun no entiendo como se hace lo de javascript

2023-03-20 05:38 UTC, giocompany reviewed
Saludos Mary! Muy buen trabajo en el uso de HTML semántico y CSS! Vamos por ese Fullstack :)

2023-03-21 07:34 UTC, NoaSalgado approved these changes
Genial, buen trabajo! 💪

2023-03-22 02:45 UTC, giocompany approved these changes

2023-03-29 01:41 UTC, merged