Semana 2- Agustina Romero
undefined-academy/semana-2 pull request #221
Opened 2023-03-26 18:41 UTC by Romero-Agustina

### **Semana 2 **
Incluyo mi html estructurado semánticamente y con el agregado de un pequeño formulario de contacto, además de una hoja de estilos donde principalmente estilo el formulario.

Esta semana el uso de git y github fueron mucho más fáciles y ya no me costó tanto como la semana anterior.

2023-03-28 22:34 UTC, diirf requested changes
Hola! Solo te he dejado una recomendación y dos cosas por cambiar

2023-03-28 22:34 UTC, diirf commented on student-cvs/Agus-Romero-8899/index.html
> +        <form>
Deberías añadir el atributo "method" en el formulario

2023-03-28 22:34 UTC, diirf commented on student-cvs/Agus-Romero-8899/index.html
> +              </textarea>
Tienes unos espacios al cerrar la etiqueta <textarea>. Eso hace que en la parte del mensaje ya comience con espacion en blanco y no permite la verificación. Coloca `<textarea id="comment" name="comment" required rows="5"></textarea>` (sin los espacios) para que no te ocurra

2023-03-28 22:34 UTC, diirf commented on student-cvs/Agus-Romero-8899/index.html
> +          <li><a href="#about">About</a></li>
Esta parte me gusta mucho, no sabía como hacerlo

2023-03-28 22:34 UTC, diirf commented on student-cvs/Agus-Romero-8899/styles.css
> +    margin: 100px auto;
Puedes agregar más estilos al resto de la página, así como el formulario

2023-04-04 20:36 UTC, Romero-Agustina commented on student-cvs/Agus-Romero-8899/index.html
> +        <form>
gracias, lo voy a revisar!

2023-04-04 20:38 UTC, Romero-Agustina commented on student-cvs/Agus-Romero-8899/index.html
> +              </textarea>
Excelente no me había dado cuenta, lo voy a corregir!

2023-04-04 21:20 UTC, Romero-Agustina commented on student-cvs/Agus-Romero-8899/styles.css
> +    margin: 100px auto;
Realicé los cambios si quieres revisar y aprobar. Gracias por tu review!

2023-04-06 09:53 UTC, diirf approved these changes

2023-05-15 02:25 UTC, closed without merging