Semana 2 - HTML SEMANTICO
undefined-academy/semana-2 pull request #23
Opened 2023-03-14 22:33 UTC by bEERRE96

- Se agregaron etiquetas para obtener un formato de HTML Semantico a nuestra hoja de vida.

2023-03-16 02:43 UTC, Alexis033 requested changes

2023-03-16 02:43 UTC, Alexis033 commented on student-cvs/bR-3929/index.html
> +    <section>
Hola, yo diría que en esta parte sería, más bien al contrario, todo este pedazo sería un article sobre los comandos y tendría dos section, si ves toda esta parte tiene un solo h1 que engloba todo.

2023-03-16 02:43 UTC, Alexis033 commented on student-cvs/bR-3929/index.html
> +            <h3>Comandos de la terminal aprendidos</h3>
Es raro semánticamente que pases de un h1 a un h3 sin un h2, si lo que te preocupa es el tamaño puedes configurarlo con el css.

2023-03-16 02:43 UTC, Alexis033 commented on student-cvs/bR-3929/style.css
> +body {
Ten cuidado con el contraste entre el fondo y algunas letras.

2023-03-16 22:59 UTC, Alexis033 approved these changes

2023-03-21 22:24 UTC, Matipela approved these changes

2023-03-22 10:35 UTC, merged