Se agregan etiquetas html semanticas
undefined-academy/semana-2 pull request #234
Opened 2023-03-28 01:27 UTC by Gaston095

# SEMANA 2

## PASOS PARA RESOLVER EL EJERCICIO 1
1- Primero hice **FORK** del repositorio Undefined-Academy-semana2.
2- Después clonar el repositorio **FORK** en mi home.
3- Crear un archivo **HTML** aplicando las etiquetas semánticas y agregar estilos en un archivo **CSS**.
4- Con los comandos **gitt add, git commit y git push subi** el proyecto al repositorio de la semana 2.
5- Crear un nuevo **Pull Request** de la semana 2.

2023-03-30 03:27 UTC, anthonytorres30 commented
Hola, buenas noches, muy buen trabajo el que realizaste, podrias extender el formulario a otro archivo .html y llamarlo desde el index.html, asi estaria un poco mas ordenado, del resto todo muy bien, sigue asi!

2023-03-30 15:41 UTC, diirf requested changes
Hola! Te he dejado unas sugerencias y unos pequeños cambios. Me ha gustado tu página.

2023-03-30 15:41 UTC, diirf commented on student-cvs/Gaston095-2770/script.js
> +document.getElementById("button").addEventListener("click", function(event){
Tal y como tienes el script no deja que se valide ningún campo del formulario, puedes enviar el formulario vacío. Debes usar el evento "submit" en vez de "click", ya que éste se activa cuando se envía el formulario. Si le das inspeccionar a la página verás que te va a ir contando los click del botón enviar. No sé si querías mostrar una ventana emergente con el mensaje "presionaste enviar datos" pero, el `console.log` te va a mostrar el mensaje en consola, si prefieres lo anterior utiliza un `alert()`

2023-03-30 15:41 UTC, diirf commented on student-cvs/Gaston095-2770/index.html
> +            <label class="block" for="phone">Telefono</label>
Si quieres, para validar que solo se introduzca un número de tlf puedes usar el atributo `pattern="[0-9]+"`

2023-03-31 14:29 UTC, Gaston095 commented on student-cvs/Gaston095-2770/index.html
> +        <p>Estoy cursando el bootcamp de <a class="name" href="https://undefined.academy/">Undefined Academy</a></p>
si, es muy buena sugerencia! ya lo implemente!

2023-03-31 14:32 UTC, Gaston095 commented on student-cvs/Gaston095-2770/index.html
> +        <a href="github.com">Link a github</a>
Tienes razón, lo puse así desde que cree el markdown y luego no lo edite.

2023-03-31 14:46 UTC, Gaston095 commented
Muchas gracias por tus sugerencias y cambios! ya los aplique!

2023-04-03 19:00 UTC, JoeOsG commented on student-cvs/Gaston095-2770/images/img-header.jpg
Imagen duplicada.

2023-04-03 19:09 UTC, Gaston095 commented on student-cvs/Gaston095-2770/images/img-header.jpg
Listo ya elimine la duplicada!

2023-04-03 19:13 UTC, JoeOsG approved these changes
### Bien

2023-04-03 19:21 UTC, merged