camilol-1734
undefined-academy/semana-2 pull request #240
Opened 2023-03-28 15:38 UTC by camilol1021

2023-03-29 17:14 UTC, lucianogarriga requested changes
Veo un buen trabajo de HTML semántico y buena estructura de archivos en general. Recomendaría redactar el contenido de la web en un solo idioma, y agregar el archivo README.md junto a la pull request, como solicitó guillermo (para evitar el cuadro vacío al momento de realizar la PR). Avísame cuando corrijas esos detalles mínimos y te apruebo tu PR!

2023-03-29 17:14 UTC, lucianogarriga commented on student-cvs/camilol-1734/index.html
> +            <ul>
Como recomendación te diría que redactes el cuerpo de tu sitio en un solo idioma, todo en inglés o todo en español.

2023-03-29 21:20 UTC, dfm555 commented on student-cvs/camilol-1734/index.html
> +            <ul>
@camilol1021 buena recomendación que te hizo luciano.

2023-03-30 13:19 UTC, dfm555 requested changes
Realiza los cambios sugeridos.

2023-03-31 22:59 UTC, dfm555 requested changes
agrega el .gitignore file y elima la carpeta node_modules

2023-04-01 01:07 UTC, closed without merging