Exercises (Week 2)
undefined-academy/semana-2 pull request #242
Opened 2023-03-28 16:39 UTC by r4vc31

2023-03-29 17:07 UTC, lucianogarriga requested changes
En líneas generales veo que has realizado un buen trabajo! Como recomendación, la cuestión señalada sobre no dar estilos sobre el mismo HTML con etiquetas como em o strong, y faltaría agregar un archivo .md a la hora de hacer una descripción del trabajo realizado en tu pull request. Avisame cuando modifiques esas cuestiones para aprobar tu PR!

2023-03-29 19:18 UTC, lucianogarriga approved these changes
Gran trabajo, luego de la corrección de las recomendaciones, me parece que tu PR cumple con lo solicitado para ser aprobada!

2023-04-27 13:32 UTC, EzequielCaste approved these changes
Todo se ve muy bien :+1: 

Hice un comentario pero no creo que sea algo tan grave.

Lo que sí te voy a recomendar es que trates de usar colores de texto que hagan contraste con el color del fondo. En Chrome puedes inspeccionar el texto para ver si el contraste es el adecuado:

![image](https://user-images.githubusercontent.com/51804994/234877340-0f0a19d1-d009-40ea-896b-cbd2815489e2.png)

Aquí te sale una advertencia, indicando que el contraste entre texto y fondo no es ideal.

Es una cuestión de accesibilidad para personas con problemas de vista.

2023-04-27 13:32 UTC, EzequielCaste commented on student-cvs/r4vc31-7548/index.html
> +    <footer></footer>
```suggestion
    <footer></footer>
```

eliminar este Footer vacio.

2023-04-27 20:56 UTC, r4vc31 commented on student-cvs/r4vc31-7548/index.html
> +    <footer></footer>
Muchas gracias por las recomendaciones, subiré los cambios indicados.

2023-04-28 13:56 UTC, merged