gab-3881 - Semana 2 - PR
undefined-academy/semana-2 pull request #248
Opened 2023-03-29 17:04 UTC by ga-b0

Para los ejercicios correspondientes a la semana-2: 

1. Realicé un fork del repositiorio
2. Cloné el repositorio al cual le hice fork
3. Validé mi HTML
4. Tomé como punto de partida el HTML y CSS creados en la semana anterior
5. Hice desde cero el HTML y CSS de mi nuevo perfil, añadí nuevas cosas y lo modifiqué para que tuviera sentido semántico.
6. Añadí un formulario de contacto al final de mi documento HTML

2023-03-31 00:54 UTC, MauBedoya requested changes
Creo que sería bueno darle una mirada al uso de tus `article` 👀. 
Para separar "partes" del contenido de una página se usan los `section`.

2023-03-31 00:54 UTC, MauBedoya commented on student-cvs/gab-3881/index.html
> +    <article>
me parece que la etiqueta correcta aquí es `main`, que indica que es el contenido principal de tu CV y es contenido relacionado entre sí, al usar `article` estarías dando a entender que es una parte no relacionada a tu CV en sí.

2023-03-31 00:54 UTC, MauBedoya commented on student-cvs/gab-3881/index.html
> +    <article>
este `article` no es necesario, parece que lo intentas usar para separar el contenido del anterior (del que te recomiendo que este englobado en un `main`), la función de separar el contenido en partes ya la cumple la etiqueta `section`

2023-03-31 00:54 UTC, MauBedoya commented on student-cvs/gab-3881/styles.css
> +    resize: vertical;
como detalle... quizá sería mejor dejar el resize en `none`, es un poco raro que los textarea se permitan redimensionar.

2023-04-03 15:19 UTC, ga-b0 commented on student-cvs/gab-3881/index.html
> +    <article>
Tienes razón, muchas gracias por el comnetario

2023-04-03 15:20 UTC, ga-b0 commented on student-cvs/gab-3881/index.html
> +    <article>
Ya hice las correcciones, muchas gracias por el comentario

2023-04-03 17:29 UTC, MauBedoya approved these changes
Esta corregido el tema de la semántica de los **article** 👌
Solo dos cositas menores que revisar pero en si ya estaría me parece.

2023-04-03 17:29 UTC, MauBedoya commented on student-cvs/gab-3881/index.html
> +        <section>
esta `section` no es necesaria ya que no está separando ningún contenido interno de **main**. En si ahora **main** es tu "sección" por lo que no hace falta otra etiqueta semántica que englobe todo el mismo contenido.

2023-04-03 17:29 UTC, MauBedoya commented on student-cvs/gab-3881/styles.css
> +.form-group input:not([type="checkbox"]), .form-group textarea, label {
recuerda que para "bloquear" el redimensionamiento del **textarea** debes usar:
```css
textarea {
    resize: none;
}
```
Creo que si pones el **resize** en este selector debería funcionar de igual manera

2023-04-03 17:40 UTC, ga-b0 commented on student-cvs/gab-3881/styles.css
> +.form-group input:not([type="checkbox"]), .form-group textarea, label {
Muchas gracias, se me escapó editar esa parte, pero ya mismo lo hago, muchas gracias por las correcciones

2023-04-03 21:31 UTC, sheifg commented
Hola Gabriel
Muy buenas recomendaciones por parte de @MauBedoya!
Me gusta como te han quedado :)

2023-04-03 21:33 UTC, sheifg approved these changes

2023-04-04 13:16 UTC, dfm555 approved these changes

2023-04-04 13:16 UTC, merged