cambios
undefined-academy/semana-2 pull request #258
Opened 2023-04-01 02:17 UTC by camilol1021

1. Hice fork del repositorio de la semana-2
2. luego en la carpeta de students integre el html y css con las indicaciones responsive inicadas
3. luego ejecute el commit y al push 
4. por ultimo lo hize el pull request

2023-04-03 15:33 UTC, ga-b0 requested changes

2023-04-03 15:33 UTC, ga-b0 commented on student-cvs/camilol-1734/index.html
> +                <h3>my studies</h3>
Aquí no deberías poner el `<h3>` dentro del `<ul>` pues no es hijo de esa etiqueta, en lugar de ello puedes dejarlo afuera y ponerlos antes que el `<ul>`

2023-04-03 15:33 UTC, ga-b0 commented on student-cvs/camilol-1734/index.html
> +                <h4>Know about me 😁</h4>
Los mismo, el `<h4>` dejalo afuera del `<ul>`

2023-04-03 15:33 UTC, ga-b0 commented on student-cvs/camilol-1734/index.html
> +                <h3>Experience</h3>
Aquí también el `<h3>` fuera del `<ul>`

2023-04-04 19:14 UTC, camilol1021 commented
es que los deje adentro porque visualmente se ve mejor y centrado

El lun, 3 abr 2023 a las 10:34, Gabriel Calderón ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In student-cvs/camilol-1734/index.html
> <https://github.com/undefined-academy/semana-2/pull/258#discussion_r1156124146>
> :
>
> > +    <meta charset="UTF-8">
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +    <title>Document</title>
> +    <link rel="stylesheet" href="styles.css">
> +
> +</head>
> +<body>
> +    <main>
> +        <nav> <h1 class="lines-effect"><em>!! I'm camilo castañeda</em></h1></nav>
> +        <h2>Development of apps mobile</h2>
> +            <p>I want to learn Software development for my futures jobs and personal growth, Im kind and respectful <strong> Im from Colombia</strong> </p>
> +        <section class="content">
> +
> +            <ul>
> +                <h3>my studies</h3>
>
> Aquí no deberías poner el <h3> dentro del <ul> pues no es hijo de esa
> etiqueta, en lugar de ello puedes dejarlo afuera y ponerlos antes que el
> <ul>
> ------------------------------
>
> In student-cvs/camilol-1734/index.html
> <https://github.com/undefined-academy/semana-2/pull/258#discussion_r1156125934>
> :
>
> > +    <main>
> +        <nav> <h1 class="lines-effect"><em>!! I'm camilo castañeda</em></h1></nav>
> +        <h2>Development of apps mobile</h2>
> +            <p>I want to learn Software development for my futures jobs and personal growth, Im kind and respectful <strong> Im from Colombia</strong> </p>
> +        <section class="content">
> +
> +            <ul>
> +                <h3>my studies</h3>
> +                <li>👻Development for mobile apps</li>
> +                <li>👻Excel advanced intermediate</li>
> +                <li>👻Computer segurity and controls </li>
> +            </ul>
> +        </section>
> +        <section class="signup">
> +            <ul>
> +                <h4>Know about me 😁</h4>
>
> Los mismo, el <h4> dejalo afuera del <ul>
> ------------------------------
>
> In student-cvs/camilol-1734/index.html
> <https://github.com/undefined-academy/semana-2/pull/258#discussion_r1156127119>
> :
>
> > +                <li>👻Computer segurity and controls </li>
> +            </ul>
> +        </section>
> +        <section class="signup">
> +            <ul>
> +                <h4>Know about me 😁</h4>
> +                <li><a href="https://github.com/camilol1021">GitHub</a></li>
> +                <li><a href="https://www.linkedin.com/in/camilo-casta%C3%B1eda-9602ab23b/">Linkedin</a></li>
> +                <li><a href="contacto.html">contact</a></li>
> +            </ul>
> +        </section>
> +        <div class="features">
> +        <section class="feature">
> +
> +            <ul>
> +                <h3>Experience</h3>
>
> Aquí también el <h3> fuera del <ul>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/undefined-academy/semana-2/pull/258#pullrequestreview-1369287648>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWWYTCQ44I6C6DJEMUZBZNLW7LUWTANCNFSM6AAAAAAWPKIEUY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-04 21:17 UTC, dfm555 requested changes

2023-04-04 21:17 UTC, dfm555 commented on student-cvs/camilol-1734/index.html
> +                <h3>my studies</h3>
@camilol1021 debes corregirlo pues no es correcto, para conseguir el efecto que deseas usa css.

2023-04-05 03:49 UTC, camilol1021 commented on student-cvs/camilol-1734/index.html
> +                <h3>my studies</h3>
Listo ya cambie los h3 en el index y el css ya esta centrado el titulo, muchas gracias

2023-04-05 13:14 UTC, dfm555 approved these changes

2023-04-05 13:14 UTC, merged