Ejercicio-semana2
undefined-academy/semana-2 pull request #262
Opened 2023-04-02 03:13 UTC by sebasricop

Ejercicio 2 , semana 2.
Seguimos avanzando con toda.

2023-04-02 11:41 UTC, VicBocanegra25 requested changes
Hola estimado Sebastián. 

Revisé tu archivo html y me parece que está bien dividido en secciones, por lo que se cumple con el requisito puesto en la clase de HTML Semántico.

Me gustaría ofrecerte una retroalimentación en dos cosas. Pienso que tu información de contacto podría ir en el footer (como lo dice Guillermo durante la clase) y que la parte de "How to reach me" en donde pones tu correo y tu github podría ir agregada a la parte de Connect with me.

Además, como veo que estás aprendiendo inglés, te sugiero que uses la aplicación Grammarly para realizar correcciones de estilo/ortografía o que uses chatgpt para ello. Aquí una sugerencia del cambio en la descripción: 

"Passionate frontend developer from Medellin, I enjoy working in a team environment. I am a cooperative and happy individual, always open to new learning opportunities."

Saludos desde México.

2023-04-03 02:45 UTC, sebasricop commented
De una, mil gracias por tu  ayuda, tomare tus recomendaciones y corregiré el archivo, un saludo.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: domingo, 2 de abril de 2023 6:41 a. m.
To: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Subject: Re: [undefined-academy/semana-2] Ejercicio-semana2 (PR #262)


@VicBocanegra25 requested changes on this pull request.

Hola estimado Sebastián.

Revisé tu archivo html y me parece que está bien dividido en secciones, por lo que se cumple con el requisito puesto en la clase de HTML Semántico.

Me gustaría ofrecerte una retroalimentación en dos cosas. Pienso que tu información de contacto podría ir en el footer (como lo dice Guillermo durante la clase) y que la parte de "How to reach me" en donde pones tu correo y tu github podría ir agregada a la parte de Connect with me.

Además, como veo que estás aprendiendo inglés, te sugiero que uses la aplicación Grammarly para realizar correcciones de estilo/ortografía o que uses chatgpt para ello. Aquí una sugerencia del cambio en la descripción:

"Passionate frontend developer from Medellin, I enjoy working in a team environment. I am a cooperative and happy individual, always open to new learning opportunities."

Saludos desde México.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fundefined-academy%2Fsemana-2%2Fpull%2F262%23pullrequestreview-1368068662&data=05%7C01%7C%7C3fb187509a3c493c73e008db336f3a41%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638160325044468826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gPCJpTqlOjayhsnQ%2BxwCAW6Xnao7H4I%2Fu2vnaevTAS0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUN6MV7ZOAJB7XNGIVUKNELW7FQXJANCNFSM6AAAAAAWQAYENU&data=05%7C01%7C%7C3fb187509a3c493c73e008db336f3a41%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638160325044625075%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cuEctUYaTZrY1iySSK0p1ygj2gDparEV%2B4FBmQqY77Q%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-03 03:15 UTC, sebasricop commented
Hola Víctor Eduardo, muchas gracias por tu ayuda, realizare el cambio que me sugieres, ya revise en la aplicación Grammarly y tienes razón, estaba muy mal la gramática en ingles.

2023-04-04 03:59 UTC, VicBocanegra25 approved these changes
Excelente! Commit revisado.

2023-04-23 13:59 UTC, DevOld112 approved these changes
Compañero lo veo todo bien, tiene mi approve

2023-04-23 19:47 UTC, merged