html semantico- version 01
undefined-academy/semana-2 pull request #267
Opened 2023-04-03 23:31 UTC by Lunisa202

##HTML Semántico
1. He creado un archivo html con el formato de una hoja de vida.
2. Le di estilos con CSS para que tuviera color y se vea bien el pantalla de pc, aun no está responsive.
3. Pase mi codigo html por el [validador](https://validator.w3.org/), y no me lanzó errores.
4. Agregé los archivos con git add a la lista de archivos trackeados, luego git commit, y al final git push origin main.

2023-04-05 17:02 UTC, Lunisa202 commented
## Formularios
1. He agregado un formulario de contacto y lo enlacé a la pagina principal.
2. Agregé algunos estilos en CSS a la pagina de contacto.html.
3. Hice el commit con los cambios y git push.

2023-04-05 20:51 UTC, gabobregon89 reviewed
Buenas, lo veo todo muy bien armado y ordenado, lo que si para mi la primer parte de home, biography y certificados estaria demás, al igual que al final los contactos de redes sociales, porque lo que creo del formulario tendria que estar enfocado en hacerte un pedido de proyecto directo y no tener que estar viendo otras cosas, eso todo lo mandaria al index.

2023-04-05 21:53 UTC, MauBedoya approved these changes
Muy bueno tu trabajo con las etiquetas semánticas 👌.
Solo unos comentarios por cositas pequeñas.

2023-04-05 21:53 UTC, MauBedoya commented on student-cvs/Carolina08001-6984/contact.html
> +        <input type="tel" name="telefono" placeholder="Enter yor phone number"
aquí parece que te falto pone el **id** para que se enlace al **label**

2023-04-05 21:53 UTC, MauBedoya commented on student-cvs/Carolina08001-6984/contact.html
> +    <h1>Contacto</h1>
este **h1** parece quedar oculto por la barra de navegación, quizá habría que agregar un poco de padding-top para resolver esto (si es que no está pensado para ser así)

2023-04-05 21:53 UTC, MauBedoya commented on student-cvs/Carolina08001-6984/contact.html
> +        <input type="url" name="url">
quizá aquí tambien lo del id?

2023-04-09 18:16 UTC, Lunisa202 commented on student-cvs/Carolina08001-6984/contact.html
> +    <h1>Contacto</h1>
Hola, en el CSS si logré hacerle que el nav no tape el h1. Bueno respecto a la navegación, me pareció necesaria en esta pagina tambien, es necesario para que podamos navegar más rapido, y vi algunos sitios de otros programadores que tambien usan el nav en todas sus paginas.

2023-04-09 18:17 UTC, Lunisa202 commented on student-cvs/Carolina08001-6984/contact.html
> +        <input type="url" name="url">
Si, recién me doy cuenta de eso, lo voy arreglar. Gracias por notarlo.

2023-04-09 18:21 UTC, Lunisa202 commented
> Buenas, lo veo todo muy bien armado y ordenado, lo que si para mi la primer parte de home, biography y certificados estaria demás, al igual que al final los contactos de redes sociales, porque lo que creo del formulario tendria que estar enfocado en hacerte un pedido de proyecto directo y no tener que estar viendo otras cosas, eso todo lo mandaria al index.

Hola, el nav es generico, estaba en la primera pagina, en el index.html, lo coloqué en la otra para que tuviera consistencia todas las paginas y saber q tienen un formato establecido cada una.
Respecto a lo que pido en el formulario, es referencial, lo que quería era  usar las etiquetas de la clase, necesariamente solo estoy practicando, en un proyecto real, tendría que verificar bien qué datos debo pedir.

2023-04-09 18:27 UTC, Lunisa202 commented
> Buenas, lo veo todo muy bien armado y ordenado, lo que si para mi la primer parte de home, biography y certificados estaria demás, al igual que al final los contactos de redes sociales, porque lo que creo del formulario tendria que estar enfocado en hacerte un pedido de proyecto directo y no tener que estar viendo otras cosas, eso todo lo mandaria al index.

Lo de las redes sociales si lo he visto que muchos sitios web lo mantienen en todas sus paginas en el footer, por eso lo consideré que también estuviera en el formulario.

2023-04-09 18:34 UTC, Lunisa202 commented
1. Agregué el id que me faltaba al campo telefono del formulario. 
2. Guardé los cambios, hice git add . y git commit, para luego comprobar con git pull, y enviarlo con git push.

2023-04-09 20:25 UTC, MauBedoya commented on student-cvs/Carolina08001-6984/contact.html
> +    <h1>Contacto</h1>
ahh estas usando el nav para moverte entre páginas del sitio, ahi tienes toda la razón, es necesario en ese caso, no sé cómo se me paso el ver los enlaces 😅

2023-04-09 22:37 UTC, StephanyCS1 approved these changes
Hola, 
te quedo chevere el cv, cumple con lo solicitado en la actividad 😁

2023-04-10 01:20 UTC, Sorx4s commented on student-cvs/Carolina08001-6984/contact.html
> +          $ 1,000.00</label>
¿Estos inputs deberían ser requeridos?

2023-04-10 01:21 UTC, Sorx4s requested changes

2023-04-10 01:21 UTC, Sorx4s commented on student-cvs/Carolina08001-6984/contact.html
> +          $ 1,000.00</label>
Hay que corregir el `for`
```suggestion
          <label for="1000"><input type="radio" name="budget" id="1000" value="1000">
          $ 1,000.00</label>
```

2023-04-10 13:42 UTC, gabobregon89 approved these changes

2023-04-11 17:00 UTC, merged