aplicando html semántico
undefined-academy/semana-2 pull request #269
Opened 2023-04-04 14:03 UTC by mpchaneton

2023-04-05 02:27 UTC, gabobregon89 requested changes
Buenas, esta muy bueno el trabajo, lo unico que te podria recomendar es el uso de clases  para los tags, asi luego es mas simple aplicarle los estilos y quedaria agregar el formulario para completar la semana. Buena trabajo.

2023-04-05 14:05 UTC, gabobregon89 reviewed
Bien ahi, quedaria solo el formulario.

2023-04-06 21:37 UTC, gabobregon89 approved these changes

2023-04-14 19:58 UTC, zucerkia approved these changes
todo ok 👍🏼

2023-04-14 19:58 UTC, Seujumon approved these changes
Bárbaro. Cumple muy bien lo que nos pedían. 
Éxitos en lo que resta del bootcamp

2023-04-14 20:56 UTC, Yanina-Unrein approved these changes
buenísimo cumple con todo!

2023-04-17 20:57 UTC, merged