Semana2
undefined-academy/semana-2 pull request #272
Opened 2023-04-04 23:41 UTC by rafaelruizdev

# Ejercicio Clase 3 HTML semántico
1. Verifico el outline en https://validator.w3.org/nu/ de index.html.
2. Corrijo algunos errores.
3. Añado algunas etiquetas en el index.html para hacer uso de etiquetas semánticas.
4. Realizo el fork del repositorio de la semana 2
5. Hago el PR.

2023-04-05 00:04 UTC, manuelmannuel requested changes
Excelente, solo me parece que faltaria el formulario.

2023-04-05 01:04 UTC, taliixer reviewed
Hola rafi, en general vas muy bien, pero aún te hace falta completar la parte del formulario de contacto básico donde las personas van a poder ponerse en comunicación contigo

2023-04-05 02:18 UTC, gabobregon89 requested changes
Buenas, el index.html cumple con la semantica, lo unico que te podria recomendar es que uses clases para los tags, para asi poder hacer una mejor referencia al momento de dar estilo.

2023-04-06 00:33 UTC, rafaelruizdev commented
# Ejercicio Clase Formulario HTML
1. Reviso los comentario dados por la comunidad en mi html.
2. Creo el formulario de contacto en una página diferente y sus estilos.
3. Realizar el script para controlar la acción del botón.
4. Hago el Commit y el PR de la actividad.

2023-04-06 00:36 UTC, rafaelruizdev reviewed
Acabo de realizar el commit y el PR con el formulario.

Gracias por los comentarios.

2023-04-06 00:36 UTC, rafaelruizdev reviewed
Acabo de realizar el commit y el PR con el formulario.

Gracias por los comentarios.

2023-04-06 00:38 UTC, rafaelruizdev reviewed
He modificado el html y el css para crear mas clases, además de crear el formulario de contacto

Gracias por los comentarios.

2023-04-06 00:38 UTC, manuelmannuel approved these changes

2023-04-06 17:56 UTC, 4ngelo12 approved these changes

2023-04-06 21:34 UTC, gabobregon89 approved these changes

2023-04-06 21:43 UTC, manuelmannuel approved these changes

2023-04-08 14:55 UTC, taliixer approved these changes

2023-04-09 13:30 UTC, merged