Modificar html con etiquetas semanticas
undefined-academy/semana-2 pull request #282
Opened 2023-04-06 19:59 UTC by rodrigosoberon

Cambios realizados:

- Fork de repositorio semana-2
- Copiar archivos realizados en semana-1
- Cambiar html para agregar etiquetas semánticas
- Crear pull request

2023-04-11 18:04 UTC, lucianogarriga requested changes
En lineas generales buen trabajo! Recomiendo un breve detalle sobre el idioma del contenido de la web, y también de aplicar algún formateador a cada archivo del código, ya que se torna un poco difícil de leer.

2023-04-11 18:04 UTC, lucianogarriga commented on student-cvs/rodrigo-soberon-0682/contacto.html
> +			<a href="contacto.html">Contacto</a>
Recomiendo que todo el contenido sea en ingles, o todo en español.

2023-04-11 20:01 UTC, lucianogarriga approved these changes
Buen trabajo Rodrigo, como has visto las recomendaciones considero que tu PR está en condiciones para ser aprobada. Felicidades!

2023-04-15 02:22 UTC, dilsonalfonso commented
Se ve bien las modificaciones realizada y de acorde a la clase

2023-04-15 02:27 UTC, dilsonalfonso approved these changes
Veo todo basado en los lineamientos de la clase

2023-05-01 02:22 UTC, closed without merging