HTML Semántico + CSS -  Semana 2
undefined-academy/semana-2 pull request #294
Opened 2023-04-11 15:39 UTC by dhmaccarone

Se agrego HTML Semántico, imagen y estilos a la hoja de vida.

2023-04-12 19:28 UTC, ivanpachecos requested changes
Que tal!, corrige lo comentado y el resto Nice.

2023-04-12 19:28 UTC, ivanpachecos commented on student-cvs/Overcome18M-2787/index.html
> +        <h2>🛠️ Lenguajes y Tecnologías</h2>
Puedes hacer otra seccion para la parte de Lenguaje y tecnologías.

2023-04-13 12:45 UTC, Yanina-Unrein commented on student-cvs/Overcome18M-2787/index.html
> +<html lang="en">
Adhiero a cambiar el idioma a español por el mismo hecho que el sitio esta en español, el resto muy bueno!

2023-04-13 12:47 UTC, Yanina-Unrein approved these changes

2023-04-13 12:47 UTC, Yanina-Unrein commented on student-cvs/Overcome18M-2787/index.html
> +<html lang="en">
Adhiero a cambiar el idioma a español por el mismo hecho que el sitio esta en español, el resto muy bueno!

2023-04-30 02:21 UTC, closed without merging