Adding my files to my new directory.
undefined-academy/semana-2 pull request #30
Opened 2023-03-15 00:00 UTC by Josofico

### Hi! 

# At this time we make some changes in our index.html, like adding logic in the structure and semantic things.

2023-03-28 23:21 UTC, diirf requested changes
Hola! Te dejé solo una pequeña observación, que es más bien una pregunta

2023-03-28 23:21 UTC, diirf commented on student-cvs/Kick Off-2479/index.html
> +                <h2>I'm glad to see you here, let me tell you something <a href="about.html">about me!</a><br>
Haces referencia a un archivo "about.html" pero no existe. Quizás aún no lo has hecho?

2023-03-28 23:21 UTC, diirf commented on student-cvs/Kick Off-2479/index.html
> +                <h2>I'm glad to see you here, let me tell you something <a href="about.html">about me!</a><br>
Me gustó como integraste esta sección para ir al formulario

2023-03-28 23:21 UTC, diirf commented on student-cvs/Kick Off-2479/layout.html
> +<!DOCTYPE html>
Me gusto mucho esta página

2023-03-28 23:59 UTC, Josofico commented on student-cvs/Kick Off-2479/index.html
> +                <h2>I'm glad to see you here, let me tell you something <a href="about.html">about me!</a><br>
Es correcto, me parece que mejor lo borro, gracias por tu valiosa opinion!

2023-03-29 00:00 UTC, Josofico commented on student-cvs/Kick Off-2479/index.html
> +                <h2>I'm glad to see you here, let me tell you something <a href="about.html">about me!</a><br>
Te lo agradezco !!

2023-03-29 10:39 UTC, diirf approved these changes
Apruebo, está muy bien hecho tu trabajo

2023-03-30 02:25 UTC, Lealdos approved these changes
i think everything is done and great

2023-03-30 09:06 UTC, merged