Ejercicios Semana 2
undefined-academy/semana-2 pull request #313
Opened 2023-04-23 03:40 UTC by jorge9372

# Procedimiento 

# Primera parte
✔️Hacer fork en el repositorio que se nos fue indicado: ``` https://github.com/undefined-academy/semana-2 ```.
✔️Clonar el repositorio para acceder de forma local ```git clone <enlace o llave proporcionado en nuestro GitHub> ```.
✔️Crear un directorio que lleve por nombre nuestro usuario en **Discord**, dentro del directorio ``` student-cvs/``` .
✔️En el directorio crear un archivo .html el cual incluirá el cv con el que se ha trabajado aplicando lo aprendido en la clase de html semántico.
✔️Realizar commit: ```git commit -m ""``` y ```git push -u origin main```.

# Segunda parte
✔️Se le agregan estilos con CSS a nuestro cv.
✔️Se anexa un formulario haciendo uso de lo aprendido.
✔️Se realiza commit para las últimas modificaciones.

Finalmente se elabora el respectivo pull request correspondiente a la semana 2

2023-04-23 04:29 UTC, JoeOsG approved these changes
Bien

2023-04-24 19:27 UTC, MrRedu requested changes
Jajaja, considero que las correcciones son tan mínimas, que podrían ser hasta para fastidiar.

A parte de eso, te recomiendo pasar el código del HTML, por el W3 Validator NU (como lo explican en la clase), tienes algunos "Warning", pero nada del otro mundo.

2023-04-24 19:27 UTC, MrRedu commented on student-cvs/JorgeVillafraz-6924/index.html
> +<html lang="es">
El contenido de tu página está en inglés, así que creo que sería más acertado poner el valor del atributo lang, en `en`

2023-04-24 19:27 UTC, MrRedu commented on student-cvs/JorgeVillafraz-6924/index.html
> +                <h2>In learning</h2>
Un errorcito, super mínimo.
I'm ≠ In

2023-04-24 19:27 UTC, MrRedu commented on student-cvs/JorgeVillafraz-6924/index.html
> +                    <p>Html</p>
Creo que sería "más correcto", HTML5.
Mayúscula y el 5

2023-04-24 19:27 UTC, MrRedu commented on student-cvs/JorgeVillafraz-6924/index.html
> +        <img src="foto2.jpg">
Atributo "alt" para las imágenes, es **bastante** recomendable.

2023-04-24 19:32 UTC, MrRedu commented on student-cvs/JorgeVillafraz-6924/index.html
> +                <h2>In learning</h2>
Ahora que lo veo, está bien 🤡

2023-04-24 19:34 UTC, MrRedu commented
Muy buen diseño, por cierto.

2023-04-24 19:43 UTC, jorge9372 commented
> Jajaja, considero que las correcciones son tan mínimas, que podrían ser hasta para fastidiar.
> 
> A parte de eso, te recomiendo pasar el código del HTML, por el W3 Validator NU (como lo explican en la clase), tienes algunos "Warning", pero nada del otro mundo.

Gracias @MrRedu , si pasa que cuando fui agregando cositas se desordenó un poco, pero bueno para eso estamos aprendiendo.

2023-04-24 21:00 UTC, MrRedu approved these changes

2023-04-24 21:58 UTC, merged