HTML semántico y página de contacto
undefined-academy/semana-2 pull request #336
Opened 2023-05-15 20:54 UTC by Alepsss

# En éste PR realicé los siguientes ejercicios:
1.-Modifiqué el código de mi CV agregandole las **etiquetas semánticas**.
2.-Creé una nueva *página HTML de contacto* con su respectivo **formulario** y estilo en CSS.

--(Nota: Al código de la página de contacto le agregué de igual manera **etiquetas semánticas**, más no sé si esté en lo correcto, me podrían hacer saber si está bien o mal, por favor.)

2023-05-17 09:27 UTC, diirf requested changes
Hola, me ha gustado mucho tu página. Te dejé solo unas pequeñas modificaciones.

2023-05-17 09:27 UTC, diirf commented on student-cvs/Aleps-5699/contact.html
> +                    <input type="checkbox" name="terms" id="terms" re4>
Te falta añadir el `required` al `checkbox` para que haga la comprobación.

2023-05-17 09:27 UTC, diirf commented on student-cvs/Aleps-5699/contact.html
> +                <form action="/server" method="get">
Falta prevenir el comportamiento por defecto del envío de la información al servidor.

2023-05-17 09:27 UTC, diirf commented on student-cvs/Aleps-5699/index.html
> +                <li><a href="/contact.html">Contacto</a></li>
La ruta absoluta está bien, pero te sugiero que la cambies a relativa porque al descargar los proyectos para evaluarlo y visualizarlo desde el servidor no encuentra el fichero.

2023-05-18 02:02 UTC, Alepsss commented
@diirf Ya quedaron corregidos los detalles que me comentaste, muchas graciassss por tus comentarios.
Espero esté correcto, ¿qué te parece?

2023-05-18 09:27 UTC, diirf approved these changes
Genial!

2023-05-20 11:38 UTC, merged