Pull Request - Semana 02
undefined-academy/semana-2 pull request #34
Opened 2023-03-15 01:09 UTC by DevOld112

# Ejercicios Bootcamp Semana-2:

## Ejercicio de calentamiento - Ejercicio 01:

1) En el ejercicio de calentamiento definimos el valor de Hugo (let hugo = 15) y solo se imprime en pantalla lo que poseen cada uno si el valor total entre los 3 es 85
2) En el ejercicio 01 hay que demostrar que `typeof obj === "object"` para ello cree una function que queda definida asi `function idObjeto(obj) {
    return typeof obj === "object" && obj !== null;
}`
3) Le agrego la condicionante de `&& obj !== null;` para que la funcion retorne si `obj` es un objeto (true) o no (false)
4) Mando a imprimir en pantalla `console.log(idObjeto(obj)` para que muestre el resultado.

## Ejercicio de calentamiento - Ejercicio 02:

1) En el ejercicio de calentamiento simplemente define un objeto `human` que tiene caracteristicas de mi persona (nombre, edad, estatura, sexo etc..) mi objeto quedo de esta manera:  
`const human = {
    name: "Wilmer",
    edad: 30,
    sexo: "Masculino",
    estatura: 1.78,
}` 
2) En el ejercicio 02 me encontre que al intentar realizarlo con `typeof arr === "object"` no iba a funcionar debido a que solo funciona para los objetos, por ende cuando definia una function de esta manera `function idArray(arr){typeof arr === "object && arr !== null` siempre retornaba false o la consola daba error cuando mandaba a imprimir el resultado de la funcion en pantalla.
3) Por ello me di la tarea de buscar en google un poco sobre los arrays y encontre que para demostrar si un array es true o false habia que mandar a llamar a `Array.isArray()`
4) Sustitui `Array.isArray()` por `typeof` y mande a llamar a mi funcion en pantalla.

2023-03-15 14:23 UTC, achequisde requested changes
Me gusta tu pagina, y usaste el bien el HTML semantico. Hay un error en que el titulo **\<h2\>Estos son los 5 comandos\</h2\>** _no_ esta dentro de la seccion de la tabla con los comandos.

Por otra parte, pero solo como sugerencia, la seccion de contacto puede ser un footer en lugar de una section, ya que podrias agregarla como pie de pagina a varios articulos.

2023-03-16 01:24 UTC, DevOld112 commented
> Me gusta tu pagina, y usaste el bien el HTML semantico. Hay un error en que el titulo **\<h2\>Estos son los 5 comandos\</h2\>** _no_ esta dentro de la seccion de la tabla con los comandos.
> 
> Por otra parte, pero solo como sugerencia, la seccion de contacto puede ser un footer en lugar de una section, ya que podrias agregarla como pie de pagina a varios articulos.

Hola que tal? Realice las modificaciones pero se me olvidó agregar lo que me comentabas del <h2> en la tabla de excel.

Lo demás si lo hice y creo que visualmente se ve mejor. Gracias por las recomendaciones

2023-03-16 07:57 UTC, IDKJesBen approved these changes
Muy buen trabajo, alguna recomendación que podría dejar es que intentes usar una paleta de colores que sea mas amigable a la hora de leerlo. El código esta bien ordenado y es perfectamente legible. Sigue así, felicidades!!

2023-03-16 12:34 UTC, achequisde approved these changes

2023-03-20 20:13 UTC, merged

2023-03-23 17:04 UTC, dfm555 commented
@DevOld112 voy a mover el README.md a tu  carpeta personal