HTML Semantico
undefined-academy/semana-2 pull request #342
Opened 2023-05-27 21:39 UTC by ManuelArmando

Agregando semántica al HTML. No he agregado mucha diversidad de semántica ya que no lo veo muy necesario en el caso de mi pagina, sin embargo en otras practicas iré agregando mas

2023-05-29 00:03 UTC, MrRedu requested changes
¡Hola Manuel!

Tengo par de observaciones:
- Daré por hecho que te referías a un `<header>`, ya que el `<head>` pertenece al documento del HTML, y es donde se declaran las etiqueta metas y demás. No te preocupes, nada para alarmarse
![image](https://github.com/undefined-academy/semana-2/assets/73679190/f3f00a17-6f5c-4227-bbc9-e5ff0b6acdb0)
- En la última clase/ejercicio de esta semana, se nos pidió una nueva página o agregar una sección, como más cómodo se te haga, de un formulario de contacto _(https://github.com/undefined-academy/semana-2)_ y pues, no está. Así que agrégale esa sección para que cumpla con lo mínimo necesario

Cuando esté completo, me puedes etiquetar acá o en el mismo Discord para darle approved. Como gustes.
Saludos 🎉

2023-06-01 23:36 UTC, MrRedu approved these changes
### ¡Buen trabajo! 💪🏼

2023-06-19 15:38 UTC, nencodev commented
¡Todo bien! Cumple lo exigido

2023-06-19 15:39 UTC, nencodev approved these changes

2023-07-05 02:48 UTC, closed without merging