PR semana 2
undefined-academy/semana-2 pull request #347
Opened 2023-06-06 14:30 UTC by dhmaccarone

Estimados, Les comparto mi PR de la semana 2.

2023-06-06 23:22 UTC, EzequielCaste requested changes
Hay un problemita con los colores que has elegido. Se recomienda que los colores del texto se contrasten bien con el color de fondo.

El Chrome Dev Tools tiene una herramienta para "inspeccionar" los elementos y te avisa cuando el contraste está mal.

https://web.dev/i18n/es/color-and-contrast-accessibility/

2023-06-06 23:22 UTC, EzequielCaste commented on student-cvs/Overcome18M-2787/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
Puede ser que se haya duplicado estas dos líneas?
`<link rel="preconnect" href="https://fonts.googleapis.com" />`
`<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />`

2023-06-06 23:22 UTC, EzequielCaste commented on student-cvs/Overcome18M-2787/index.html
> +    <title>Document</title>
Podrías agregar algo más específico, de qué trata la página? es tu CV? de quíen es?

2023-06-06 23:22 UTC, EzequielCaste commented on student-cvs/Overcome18M-2787/contacto.html
> +    <title>Document</title>
que tal? "Formulario de Contacto" ?

es una idea

2023-06-07 15:58 UTC, dhmaccarone commented
@EzequielCaste Muchas gracias por tus comentarios. Ya hice commit de las correcciones indicadas. Sabes  en que momento se utiliza git pull ?

2023-06-29 02:45 UTC, closed without merging