creando html y estilos
undefined-academy/semana-2 pull request #37
Opened 2023-03-15 01:23 UTC by Mfassi96

# Actividad semana 2 clase 3
## HTML semantico

2023-03-19 00:43 UTC, JoseCamilo84 requested changes

2023-03-19 00:43 UTC, JoseCamilo84 commented on student-cvs/Mfassi-2651/index.html
> +    <h2>
Hola... que tal . Creo que este h2 deberías de colocarlo dentro de una etiqueta padre xq está en el aire, es decir no está envuelta en algún contenedor

2023-03-19 01:55 UTC, Mfassi96 commented on student-cvs/Mfassi-2651/index.html
> +    <h2>
Hola José, gracias por la observacion, ya realize los cambios, me lod podrias aceptar?

2023-03-19 04:00 UTC, JoseCamilo84 approved these changes

2023-03-20 16:14 UTC, jaardila-3 requested changes
revisar formulario

2023-03-21 03:04 UTC, jaardila-3 approved these changes
todo acorde a las instrucciones del ejercicio

2023-07-19 15:47 UTC, closed without merging