Reestructuración con HTML semántico
undefined-academy/semana-2 pull request #40
Opened 2023-03-15 02:06 UTC by fjquants

Es este ejercicio logré reforzar lo aprendido en la semana anterior.

Realicé cambios en el contenido de la información tomando como referencia lo visto en otros PR.

Pasos seguidos:
1. Fork y  cloné la carpeta.
2. Cambios en los archivos, realización del ejercicio
3. PR desde consola

2023-03-16 02:37 UTC, fjquants commented
Pude validar mi archivo html con el validador, se encontraron varios errores que pude finalmente resolver

2023-03-28 17:19 UTC, dhdarken requested changes

2023-03-28 17:19 UTC, dhdarken commented on student-cvs/index.html
> +                    <li>Phyton</li>
una ul dentro de un p creo que es mala practica semantica , creo que para esto se podrian utilizar 2 p

2023-03-28 18:47 UTC, fjquants commented on student-cvs/index.html
> +                    <li>Phyton</li>
Toda la razon, ya lo arreglé

2023-04-14 21:15 UTC, Yanina-Unrein commented on student-cvs/fjquant-2458/form.html
> +<html lang="en">
como buen practica cambiar el idioma ya que esta en español la página, lang="es"

2023-04-14 21:18 UTC, Yanina-Unrein commented on student-cvs/fjquant-2458/index.html
> +     <div class="navegador">
el div no es necesario para contener la etiqueta nav

2023-04-14 21:21 UTC, Yanina-Unrein approved these changes
faltaría prevenir el comportamiento por defecto del envío de la información al servidor, que no vi si estaba, si esta mil disculpas

2023-04-25 02:48 UTC, andrealvarez2d approved these changes
Bien, cumple con lo planteado para esa semana

2023-04-25 15:58 UTC, merged