html semantico
undefined-academy/semana-2 pull request #43
Opened 2023-03-15 03:27 UTC by jmendezr85

creacion de html semantico utilizado lo aprendido en clase, como etiquetas article, section, etc .

2023-03-20 19:14 UTC, gustavo-arana requested changes
Hola Jorge

2023-03-20 19:14 UTC, gustavo-arana commented on student-cvs/jorgemr85-3672/index.html
> +    <title>Document</title>
Deberías darle un titulo a tu documento, recuerda que es la información que vez en el tab del navegador.

2023-03-23 01:35 UTC, jmendezr85 commented on student-cvs/jorgemr85-3672/index.html
> +<html lang="en">
ok gustavo muchas gracias, voy a aplicarle esos cambios.

2023-03-23 01:57 UTC, gustavo-arana approved these changes

2023-07-26 02:27 UTC, closed without merging