Dr.Lack47-4891
undefined-academy/semana-2 pull request #45
Opened 2023-03-15 05:11 UTC by DrLack47

Hey, this is the PR that attach the second week exercises

2023-04-16 22:53 UTC, INGCapaDev approved these changes
Buen trabajo compañero, solo te deje unas pequeñas recomendaciones.

2023-04-16 22:53 UTC, INGCapaDev commented on student-cvs/Dr.Lack47-4891/index.html
> +        <div class="body">
Buenas, te recomendaria cambiar la etiqueta `div` de esta linea por la etiqueta `main` para que sea mas semantico.

2023-04-16 22:53 UTC, INGCapaDev commented on student-cvs/Dr.Lack47-4891/pages/bootexercises.html
> +    <div class="body">
Buenas, te recomendaria cambiar la etiqueta div de esta linea por la etiqueta main para que sea mas semantico.

2023-04-17 17:42 UTC, DrLack47 commented on student-cvs/Dr.Lack47-4891/index.html
> +        <div class="body">
Ok, muchas gracias.

2023-04-17 17:42 UTC, DrLack47 commented on student-cvs/Dr.Lack47-4891/pages/bootexercises.html
> +    <div class="body">
Lo tendre en cuenta en los proximos PR, gracias.

2023-04-18 15:04 UTC, fedegomezc requested changes
Hola Daniel, esta buena tu hoja de vida.
Como puse en varias observaciones utiliza el validator porque hay algunas otras cosas que acomodar, algunas etiquetas de sobra. Acomoda eso así cumple con la consigna. Saludos

2023-04-19 19:10 UTC, DrLack47 commented
> Hola Daniel, esta buena tu hoja de vida. Como puse en varias observaciones utiliza el validator porque hay algunas otras cosas que acomodar, algunas etiquetas de sobra. Acomoda eso así cumple con la consigna. Saludos

Hola, muchas gracias por tus correciones. Ya revise con el validator y ahora todo parece estar bien para que por favor revises. Muchas gracias.

2023-04-19 19:10 UTC, DrLack47 commented on student-cvs/Dr.Lack47-4891/index.html
> +    <time datetime="2023-03-14 11:27"></time>
Ok, gracias

2023-04-19 19:10 UTC, DrLack47 commented on student-cvs/Dr.Lack47-4891/index.html
> +    <time datetime="2023-03-14 11:27"></time>
Listo

2023-04-19 19:10 UTC, DrLack47 commented on student-cvs/Dr.Lack47-4891/index.html
> +                        <img src="/pages/imgs/cat resting.jpg" alt="Cat resting">
Listo

2023-04-19 19:10 UTC, DrLack47 commented on student-cvs/Dr.Lack47-4891/pages/bootexercises.html
> +            <h3><a href="/">Home</a></h3>
Realizado

2023-04-19 19:27 UTC, fedegomezc approved these changes
Perfecto Daniel. 
Cumple lo requerido, paso la review a approve. Saludos!

2023-05-04 00:32 UTC, merged