added semantic tags
undefined-academy/semana-2 pull request #70
Opened 2023-03-16 01:45 UTC by monnsalgado

2023-03-19 00:50 UTC, JoseCamilo84 requested changes

2023-03-19 00:50 UTC, JoseCamilo84 commented on student-cvs/monserrat-7267/index.html
> +    <section class="intro"></section>
Hola... que tal, aquí creo que está de más esa etiqueta de cierre de "section", ya que más abajo estás cerrando esa etiqueta.

2023-03-23 17:27 UTC, JoseCamilo84 requested changes

2023-03-23 17:27 UTC, JoseCamilo84 commented on student-cvs/monserrat-7267/index.html
> +                <img src="https://unsplash.com/photos/qC2n6RQU4Vw" alt="">
Hola, deberías de colocarle en la propiedad "alt" alguna descripción por motivos de accesibilidad

2023-03-23 17:29 UTC, JoseCamilo84 commented on student-cvs/monserrat-7267/index.html
> +    <section class="intro"></section>
Además deberias realizar describir cuales fueron los pasos que realizaste para hacer tu primer fork y demás pasos en markdown, en la parte de arriba

2023-03-29 19:11 UTC, aitorias requested changes
Muy limpito, sencillo y lindo el diseño 😄 Puse algunos comentarios de apreciación personal, pero únicamente faltaría el realizar el evento para prevenir el comportamiento por defecto del `form` ! 😋

2023-03-29 19:11 UTC, aitorias commented on student-cvs/monserrat-7267/index.js
Te faltaría hacer el código en JS para prevenir el comportamiento por defecto al hacer envío del formulario (es muy sencillito)

2023-03-29 19:11 UTC, aitorias commented on student-cvs/monserrat-7267/styles.css
> +    vertical-align: middle;
Como el input ocupa el 100% de width de su elemento contenedor, esta propiedad sobraría en este caso, o no se está haciendo uso en este caso (se puede limpiar)

2023-03-29 19:11 UTC, aitorias commented on student-cvs/monserrat-7267/styles.css
> +    height: 48px;
Si pusiste `padding` tanto superior como inferior al botón, como opinión personal semi experta, no hace falta que indiques también un `height` fijo (en este caso de 48px) ya pueden entrar en conflicto y no mostrar el resultado deseado.

2023-03-29 19:11 UTC, aitorias commented on student-cvs/monserrat-7267/styles.css
> +h1 strong {
Parece que este selector no lo estás usando, ¿o bien son estilos para `h1` o bien `strong`? Por lo demás el CSS lo veo bien 😋

2023-03-29 19:35 UTC, laurelone21 commented on student-cvs/monserrat-7267/index.html
> +    <link rel="stylesheet" href="/styles.css">
Si la invocación al archivo se queda con la diagonal **/** cuando el archivo lo muevas a otro servidor o a un subdominio ya no se cargara el css porque empezara a buscar desde la raíz del mismo. como se puede apreciar en el [preview](https://htmlpreview.github.io/?https://github.com/undefined-academy/semana-2/blob/185717984867eb72a7b0859f5436f8e240f0ffd7/student-cvs/monserrat-7267/index.html) Si inspeccionas la consola, veras que marca error al cargar el archivo.

2023-07-16 03:00 UTC, closed without merging