HTML SEMANTICO
undefined-academy/semana-2 pull request #76
Opened 2023-03-16 07:00 UTC by gaston-R

# 2do Pull Request
 Este es el segundo pull request, agregue la carpeta con mi nombre de usuario de discord  y dentro dos archivos:

>`gaston-0280`
>>`index.html`
>>`main.css`

2023-03-19 12:33 UTC, VALNTNO requested changes

2023-03-19 12:33 UTC, VALNTNO commented on student-cvs/gaston-0280/index.html
> +<html lang="en">
El `<html lang="en">` está en inglés (en) y la página tiene el contenido en español (es), ese es un penaliza el SEO

2023-04-05 12:49 UTC, Cristhian-Medina requested changes
Vas bien

2023-04-05 12:49 UTC, Cristhian-Medina commented on student-cvs/gaston-0280/contacto/index.html
> +        <form >
Hace falta el script para evitar que se envíen los datos del formulario por defecto.

2023-04-05 12:49 UTC, Cristhian-Medina commented on .vite/deps_temp/package.json
Evita guardar estos archivos de configuración en Git utilizando el archivo '.gitignore'.

2023-04-05 14:15 UTC, gaston-R commented on .vite/deps_temp/package.json
Creo que ya está listo, gracias por la revisión

2023-04-05 18:54 UTC, gaston-R reviewed
Corregi los errores:
Cambie de idioma en las etiquetas meta 
Agregue el archivo index.mjs
Agregue <a> en el nav para navegar entre las paginas

2023-04-05 18:54 UTC, gaston-R commented on student-cvs/gaston-0280/contacto/index.html
> +        <form >
Ya agregue el script, gracias

2023-04-05 18:54 UTC, gaston-R commented on student-cvs/gaston-0280/index.html
> +<html lang="en">
Ya lo modifique, gracias

2023-04-05 23:58 UTC, closed without merging