Ejercio - semana 2 - HTML: Semántico
undefined-academy/semana-2 pull request #88
Opened 2023-03-16 21:58 UTC by facu1391

*  Se realizo el ejercicio de la semana 2, donde se indicaba hacer fork del repositorio "undefined-academy/semana-2".
* Posterior hacer el fork, se clono el proyecto de manera local.
* Una vez clonado el proyecto, se agrego el index y los estilos del perfil creado en la semana-1.
*  Posterior a eso se hizo una refactorización del perfil agregando HTML semántico.
*  Para finalizar se hizo el pull request.

2023-04-26 22:58 UTC, jacabrerapoli commented
Me parece muy bueno y atractivo tu curriculum en html.

2023-04-27 00:05 UTC, facu1391 commented
Muchas gracias, espero tu Approve si esta todo bien.

2023-05-03 13:02 UTC, Yanina-Unrein commented on student-cvs/facundo91-1495/index.html
> +<html lang="en">
lo mismo acá

2023-05-03 13:03 UTC, Yanina-Unrein approved these changes
me pareció bastante bien, todo en orden, solo dejo lo de cambiar el idioma

2023-05-05 04:44 UTC, Arzeus17 commented
Todo muy bien!

2023-05-05 04:56 UTC, Arzeus17 approved these changes

2023-05-06 04:04 UTC, dfm555 requested changes

2023-05-06 04:04 UTC, dfm555 commented on .vscode/settings.json
Elimina esta carpeta

2023-05-06 04:04 UTC, dfm555 commented on student-cvs/.gitignore
elimina este archivo

2023-05-08 13:45 UTC, dfm555 requested changes
Hola @facu1391 crea un .gitignore dentro de facundo91-1495 para que no subas los node modules y luego

git rm -r --cached node_modules 

git add .


git commit -m "Remove node_modules "

git push

2023-05-08 15:03 UTC, merged