cv con html semantico
undefined-academy/semana-2 pull request #94
Opened 2023-03-16 23:51 UTC by sebasvalencia

Ejercicio de la  semana 2.

Hacer el CV usando HTML Semántico.

![image](https://user-images.githubusercontent.com/7528986/225777277-92e95a69-8137-4304-a9d7-65d92338ec14.png)

2023-03-19 13:01 UTC, VALNTNO approved these changes
muy prolijo todo, muy bienn

2023-03-23 01:55 UTC, Cristhian-Medina approved these changes

2023-03-31 21:29 UTC, dfm555 requested changes
@sebasvalencia mueve el package.json, package-lock.json y el .gitignore dentro de tu carpeta
/student-cvs/sebas-9553/

2023-03-31 21:55 UTC, dfm555 requested changes
@sebasvalencia mueve el package.json, package-lock.json y el .gitignore dentro de tu carpeta
`/student-cvs/sebas-9553/`

Las dejaste en `/studen-cvs/`

2023-03-31 22:06 UTC, sebasvalencia commented
> @sebasvalencia mueve el package.json, package-lock.json y el .gitignore dentro de tu carpeta `/student-cvs/sebas-9553/`
> 
> Las dejaste en `/studen-cvs/`
Tienes razón , gracias por el catch!

2023-03-31 22:56 UTC, dfm555 approved these changes

2023-03-31 22:56 UTC, merged