html-semantico
undefined-academy/semana-2 pull request #99
Opened 2023-03-17 00:49 UTC by Ender96

En primer paso hice el fork de la semana 2, luego hice los cambios en mi html para cambiar las etiquetas que tenia a etiquetas semantica, en tercer paso cree una carpeta llamada como mi nombre de usario en discord  dentro de la carpeta students-cvs , y como ultimos pasos que  realice añadi mis archivos a dicha carpteta para luego utilizar el comando git add , realice mi commit con el comando git commit -m, y utlize el comando git push para llevar mi repositorio al github.

2023-03-20 17:30 UTC, jaardila-3 requested changes
Hola:
` <nav>` de tus redes sociales queda mejor como un seccion y al formulario le falta los name y como prevenir el evento submit

2023-03-20 18:16 UTC, joaquinesteban approved these changes
Todo correcto 👍🏼

2023-03-21 00:06 UTC, Ender96 commented
> Hola: ` <nav>` de tus redes sociales queda mejor como un seccion y al formulario le falta los name y como prevenir el evento submit
ah si verdad me falto prevenir el envio del formulario, ya lo arreglo.

2023-03-21 02:54 UTC, jaardila-3 approved these changes
No sabía del `onsubmit="return false;"`, me alegra ver tu código.

2023-04-21 04:10 UTC, merged